/**
 * Writes LangGraph brain topology as Mermaid using CompiledGraph#getGraph().drawMermaid().
 * Run from repo `adventure-v2/`: `npm run codegen:brain-mermaid`
 */
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { compiledBrainGraph } from "../src/brain/runTurnBrainGraph.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const outPath = join(__dirname, "../../../apps/web/src/brainGraphMermaid.generated.ts");

const drawable = compiledBrainGraph.getGraph();
const mermaid = drawable.drawMermaid({ withStyles: true });

const body = `/** Generated by \`npm run codegen:brain-mermaid\` — do not edit by hand. */

export const BRAIN_GRAPH_MERMAID = ${JSON.stringify(mermaid)};
`;

writeFileSync(outPath, body, "utf8");
console.log(`Wrote ${outPath}`);
