/** Generated by `npm run codegen:brain-mermaid` — do not edit by hand. */

export const BRAIN_GRAPH_MERMAID = "%%{init: {'flowchart': {'curve': 'linear'}}}%%\ngraph TD;\n\t__start__([<p>__start__</p>]):::first\n\tperceive(perceive)\n\tplan(plan)\n\tact(act)\n\t__end__([<p>__end__</p>]):::last\n\t__start__ --> perceive;\n\tact --> __end__;\n\tperceive --> plan;\n\tplan --> act;\n\tclassDef default fill:#f2f0ff,line-height:1.2;\n\tclassDef first fill-opacity:0;\n\tclassDef last fill:#bfb6fc;\n";
